cultural_historical_events = [
    "Arrival of Stamford Raffles and the establishment of modern Singapore (1819)",
    "Introduction of the Immigration Restriction Ordinance, leading to a surge of Chinese immigrants (1851)",
    "Construction of the iconic Raffles Hotel (1887)",
    "Establishment of the Straits Chinese British Association (1900)",
    "Japanese Occupation of Singapore during World War II (1942-1945)",
    "Proclamation of Singapore's independence and formation of the Republic of Singapore (1965)",
    "Creation of the Speak Mandarin Campaign to promote Mandarin Chinese (1979)",
    "Launch of the Singapore Arts Festival (1977)",
    "Formation of the National Arts Council (1991)",
    "Inauguration of the Esplanade - Theatres on the Bay (2002)",
    "Designation of Singapore Botanic Gardens as a UNESCO World Heritage Site (2015)",
    "Opening of the National Gallery Singapore (2015)",
    "Introduction of the Singapore Heritage Festival (2004)",
    "Establishment of the Peranakan Museum (2008)",
    "Inauguration of the National Museum of Singapore (2006)",
    "Launch of the Singapore Biennale, a contemporary art exhibition (2006)",
    "Formation of the Singapore Symphony Orchestra (1979)",
    "Celebration of Singapore's Bicentennial to commemorate the nation's history (2019)",
    "Establishment of the Asian Civilisations Museum (1997)",
    "Introduction of the Chingay Parade, an annual street parade (1973)"
]

festivals = [
    "Chinese New Year",
    "Thaipusam",
    "Hari Raya Puasa",
    "Good Friday",
    "Vesak Day",
    "Dragon Boat Festival",
    "Hari Raya Haji",
    "Deepavali",
    "Christmas",
    "Pongal",
    "Chingay Parade",
    "Hungry Ghost Festival",
    "Mid-Autumn Festival",
    "Nine Emperor Gods Festival",
    "Navaratri",
    "Diwali",
    "Eid al-Fitr",
    "Eid al-Adha",
    "Tamil New Year",
    "Wesak",
    "Gawai Dayak",
    "Thimithi",
    "Guru Nanak Jayanti",
    "Lantern Festival",
    "Vesakhi",
    "Loy Krathong",
    "Bon Odori",
    "Holi",
    "Pongal",
    "Maha Shivaratri",
    "Chap Goh Mei",
    "Songkran",
    "Ching Ming Festival",
    "Chhoti Diwali",
    "Onam",
    "Raksha Bandhan",
    "Baisakhi",
    "Hartalika Teej",
    "Krishna Janmashtami",
    "Ganesh Chaturthi",
    "Rama Navami",
    "Hanuman Jayanti",
    "Basant Panchami",
    "Lohri",
    "Karva Chauth",
    "Gudi Padwa",
    "Akshaya Tritiya",
    "Mahavir Jayanti",
    "Rakhi",
    "Milad un-Nabi",
    "Guru Purnima",
    "Bakrid",
    "Easter",
    "Palm Sunday",
    "Ascension Day",
    "Assumption of Mary",
    "All Saints' Day",
    "All Souls' Day",
    "Feast of the Immaculate Conception",
    "Epiphany",
    "Corpus Christi",
    "Purim",
    "Hanukkah",
    "Sukkot",
    "Shavuot",
    "Yom Kippur",
    "Rosh Hashanah",
    "Passover",
    "Simchat Torah",
    "Lag BaOmer",
    "Tu Bishvat",
    "Tisha B'Av",
    "Purim Katan",
    "Shemini Atzeret",
    "Sigd",
    "Janmashtami",
    "Guru Purnima",
    "Zoroastrian New Year",
    "Nowruz",
    "Chaharshanbe Suri",
    "Yalda Night",
    "Mid-Sha'ban",
    "Eid-e-Ghadeer",
    "Eid al-Milad",
    "Eid al-Ghadeer",
    "Eid al-Mubahila",
    "Eid al-Mawlid",
    "Eid al-Zahra",
    "Eid al-Burda",
    "Eid al-Bayd",
    "Eid al-Mubahala",
    "Eid al-Fateh",
    "Eid al-Jahiliyyah",
    "Eid al-Mukhtar",
    "Eid al-Haydari",
    "Eid al-Abbas",
    "Eid al-Ma'ida",
    "Eid al-Najaf",
    "Eid al-Qadim",
    "Eid al-Ra'id",
    "Eid al-Sa'id",
    "Eid al-Salihin",
    "Eid al-Wajib",
    "Eid al-Yarmouk",
    "Eid al-Zubair",
    "Eid al-Qurban",
    "Eid al-Qasim",
    "Eid al-Shuhada",
    "Eid al-Tariq",
    "Eid al-Thawra",
    "Eid al-Zuhr",
    "Eid al-Zubayr",
    "Eid al-Abdali",
    "Eid al-Afdal",
    "Eid al-Mansur",
    "Eid al-Nasir",
    "Eid al-Sharif",
    "Eid al-Sultan",
    "Eid al-Taher",
    "Eid al-Yahya",
    "Eid al-Zaki",
    "Eid al-Zahiri",
    "Eid al-Zahra",
    "Eid al-Zahir",
    "Eid al-Zakiyya",
    "Eid al-Zinah",
    "Eid al-Zuhra"
]

events = cultural_historical_events + festivals